In [1]:
import numpy as np


In [2]:
a= np.array([[3,23,4],
             [2,35,7]])

In [3]:
a.sum(axis=0)

array([ 5, 58, 11])

In [4]:
b= np.array([[2,3,5],
           [4,7,8]])

In [5]:
np.dot(a,b.transpose())

array([[ 95, 205],
       [144, 309]])

In [6]:
len(dir(np))

600

In [7]:
np.cross(a,b)

array([[ 103,   -7,  -37],
       [ 231,   12, -126]])

In [14]:
%%timeit
np.sort(a, axis=0, kind="mergesort")

2.27 µs ± 20.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
