In [1]:
import numpy as np

In [2]:
array1 = np.array([[2,3,4,5], [2,3,45,6]], dtype='int64')

In [3]:
print(array1)


[[ 2  3  4  5]
 [ 2  3 45  6]]


In [4]:
array1.dtype

dtype('int64')

In [5]:
array1.shape

(2, 4)

In [6]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((4,6)).dtype

dtype('float64')

In [8]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
1/array1

array([[0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.02222222, 0.16666667]])

In [10]:
array2 = np.array([2,24,5,6,7])

In [11]:
arr = array2[0:3].copy()

In [12]:
arr

array([ 2, 24,  5])

In [13]:
arr[2] = 3 

In [14]:
arr

array([ 2, 24,  3])

In [15]:
array2

array([ 2, 24,  5,  6,  7])

In [17]:
array1

array([[ 2,  3,  4,  5],
       [ 2,  3, 45,  6]], dtype=int64)

In [18]:
array1[0,2]

4