In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,100000,100000)

In [3]:
arr

arr2 = np.array([])

In [4]:
arr3 = np.array([[1,2,4,5], 
                 [1,23,4,5]])

In [5]:
arr3.shape


(2, 4)

In [6]:
arr3.T

array([[ 1,  1],
       [ 2, 23],
       [ 4,  4],
       [ 5,  5]])

In [7]:
ar = np.array([[1,2,3],
              [4,5,6],
              [7,1,0]])

In [8]:
ar[1,2]

6

In [9]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [10]:
ar.argmax()

6

In [11]:
np.where(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [12]:
np.where(ar
        )

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [13]:
ar[2,2] = 1

In [14]:
ar.flat

In [15]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
1


In [16]:
ar = ar.reshape(ar.size)
          

In [17]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 1])

In [18]:
ar2 = ar[2:6]

In [19]:
ar2

array([3, 4, 5, 6])

In [20]:
ar2[0] = 5 # changing an array created from part of an array changes original array.

In [21]:
ar #

array([1, 2, 5, 4, 5, 6, 7, 1, 1])

In [22]:
ar3 = ar.copy() # Use np.copy(array_name) to do a deep copy if you don't want to change the original array.

In [23]:
ar3

array([1, 2, 5, 4, 5, 6, 7, 1, 1])

In [24]:
ar3[0] = 9

In [25]:
ar

array([1, 2, 5, 4, 5, 6, 7, 1, 1])

In [26]:
ar3

array([9, 2, 5, 4, 5, 6, 7, 1, 1])