In [3]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
b = np.array([1,2,3,4,5,8,5,5,8,56,8,56,8,45,65,5,45,8,6,5,65,5,8,65])

In [5]:
b

array([ 1,  2,  3,  4,  5,  8,  5,  5,  8, 56,  8, 56,  8, 45, 65,  5, 45,
        8,  6,  5, 65,  5,  8, 65])

In [10]:
np.argsort(b)

array([ 0,  1,  2,  3, 15, 19,  7, 21,  4,  6, 18,  8, 17, 10, 22, 12,  5,
       13, 16, 11,  9, 20, 14, 23], dtype=int64)

In [11]:
np.argmin(b)

0

In [12]:
np.argmax(b)

14