## Basic Functions

In [1]:
import numpy as np
array1 = np.array([[3,2,6.5,7,7], [1,12,3,4,5]], dtype = "int32")
print(array1)

[[ 3  2  6  7  7]
 [ 1 12  3  4  5]]


In [2]:
array1.shape

(2, 5)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros([4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((6)).dtype

dtype('float64')

In [6]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
array1

array([[ 3,  2,  6,  7,  7],
       [ 1, 12,  3,  4,  5]])

In [8]:
1/array1

array([[0.33333333, 0.5       , 0.16666667, 0.14285714, 0.14285714],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

## Slicing

In [9]:
array2 = np.array([6,56,5,65,54,5])

In [17]:
arr = array2[4:6].copy()

In [20]:
arr

array([9, 5])

In [19]:
arr[0] = 9

In [13]:
array2

array([ 6, 56,  5, 65, 54,  5])

In [22]:
array1

array([[ 3,  2,  6,  7,  7],
       [ 1, 12,  3,  4,  5]])

In [24]:
array1[0,3]

7